### ISSUE TITLE
"Saved Layouts" submenu link renders invalid URL

### ISSUE THREAD

**Issue by Hecke29** [nk-crew/visual-portfolio#151]
In v2.12.0 the Admin-Menu-Link "Portfolio Items" > "Saved Layouts" renders a Link in Style of `/wp-admin/edit.php?post_type=portfolio&page=edit.php?post_type=vp_lists` which is an invalid URL. 
The part `edit.php?post_type=portfolio&page=` is redundant. 
The correct URL would be `edit.php?post_type=vp_lists`

![image](https://user-images.githubusercontent.com/737401/116536757-9d010900-a8e5-11eb-9b31-31488f4a2319.png)

**Comment by nk-o** [comment]
Most probably conflict comes from a 3rd-party plugin. On my side everything is correct
![image](https://user-images.githubusercontent.com/14810891/117035017-8b1bcd80-ad0c-11eb-8a1f-521b70189f75.png)
