### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by LucaGiovannetti** [nk-crew/visual-portfolio#163]
Hi, 
  I have installed Visual Portfolio on my site and ended up in a problem that seems to have already been addressed in the past and solved with a release.
It does not appear in the first images but only
This is the situation of my installation:

PHP 7.4.28
MariaDB - Server Version: 10.3.34-MariaDB-log-cll-lve - MariaDB Server
Protocollo Version: 10
Wordpress 6.0.
Visual Portfolio 2.16.0.
All plugins deactivated except “Visual Portfolio” and "Coming Soon Page, Maintenance Mode, Landing Pages & WordPress Website Builder by SeedProd".
Using the Twenty Twenty-TwoVersion: 1.2 theme, no child.
Debug mode on.

I suspect the problem is related to photos far behind.
![Cattura-Admin in the Post panel](https://user-images.githubusercontent.com/106688273/171449378-8189eb20-43b8-40a6-9c33-61c9d7dfba60.JPG)
![Cattura-Front-End Page](https://user-images.githubusercontent.com/106688273/171449406-cd0ec9a3-76f3-47d7-aa4e-8dbddd7c568b.JPG)

This is a hold post with same problem:
https://wordpress.org/support/topic/notice-trying-to-access-array-offset-on-value-of-type-bool-in-class-assets-php/

Many Thank's in advance
LG

**Comment by nk-o** [comment]
Hey.

Unfortunately, I can't reproduce this problem.

The topic you mentioned has nothing with your issue. They are completely different.
