### ISSUE TITLE
jQuery Event: init.vpf not working and no resizing on Window resize

### ISSUE THREAD

**Issue by schmoe-github** [nk-crew/visual-portfolio#164]
Hi NK Crew,

on our page https://www.omnicon.de/ the visual portfolio is not always 100% width. I want to reinit/resize the visual portfolio, when Window is fully loaded or do something else after visual portfolio is finished intializing.

But the jQuery event mentioned in the documentation:

$(document).on('init.vpf', function (event, vpObject) {
    if ( 'vpf' !== event.namespace ) {
        return;
    }

    console.log(event, vpObject);
});

is not fired at all and when I resize manually or in JS it does not resize itself as well.

So, how can I achieve to let visual portfolio reinit after the document is loaded or let visual portfolio reinit with a certein method. 

We are using

WP Bakery (6.6.0.) with Engage Theme (3.4.7.) and Visual Portfolio Free (2.17.1) on Wordpresss 6.0.0.

Kind regards,

**Comment by schmoe-github** [comment]
It's just on the homepage where these images are shown:
![visual_portfolio](https://user-images.githubusercontent.com/60428011/179758770-6d73f2a9-c347-4603-9ca4-9bc17a89ca8c.PNG)

**Comment by nk-o** [comment]
This is not a Visual Portfolio plugin.
