### ISSUE TITLE
Error when editing layouts, gallery blocks not showing

### ISSUE THREAD

**Issue by 99kero** [nk-crew/visual-portfolio#180]
Hello, I have been encountering an issue the past couple days while trying to edit my galleries. 

- First of all, when I open the page that I am trying to edit, the pictures of the galleries are not shown. Instead, all I see is the watermark loading.
![image](https://user-images.githubusercontent.com/82767049/217611083-5e4bae63-3dae-4832-bc76-32d5dc6338ff.png)

- Second, whenever I try to edit the layout of a gallery, e.g the row height, I get an error message and the block disappears. 

Would like to know what to source of the problem could be and if I can fix it of if it's out of my control. Thanks!

**Comment by nk-o** [comment]
Hey.

Have you tried to test it with a standard TwentyTwenty theme and with disabled 3rd-party plugins?

Can you also check the browser console for error text? https://balsamiq.com/support/faqs/browserconsole/

**Comment by 99kero** [comment]
Hello again.
I tried testing it with the TwentyTwenty theme and the error still pops up, and the gallery doesn't show when I am editing the page. These are the errors I got on my console: 
[99kero.com-1679864630897.log](https://github.com/nk-crew/visual-portfolio/files/11073072/99kero.com-1679864630897.log)

**Comment by 99kero** [comment]
Hello!
Problem is solved! I figured it was a Cloudflare problem. This is where I found the solution: https://visualportfolio.co/docs/troubleshooting/preview-does-not-load-in-editor/
