### ISSUE TITLE
"Move Overlay Under Image" option missing in the settings

### ISSUE THREAD

**Issue by jx1k** [nk-crew/visual-portfolio#185]
I'm missing the **Move Overlay Under Image** option in the settings of Visual Portfolio. It is mentioned in the [manual](https://visualportfolio.co/docs/portfolio-blocks/items-style/fade/) under **2 Overlay**.
It is not marked as a pro feature, so I was hoping it would be available in the free version.

**Comment by nk-o** [comment]
It is marked as a premium feature here https://visualportfolio.co/masonry-caption-move/

**Comment by jx1k** [comment]
The setting I'm referring to is listed for the Fade and Fly skin and not specified as a pro feature whereas other features specific to the pro version are. I don't see anything regarding this with the link you provided.
I attached this screenshot from the documentation of the Fade skin to clarify what I'm talking about.

<img width="704" alt="Bildschirmfoto 2023-06-25 um 11 17 38" src="https://github.com/nk-crew/visual-portfolio/assets/98455622/d81bbfd2-a628-4dff-bc38-d9114c6266c7">

**Comment by nk-o** [comment]
Oh yeah, sorry, got the setting mixed up. This setting is also part of the Pro version and is featured on this page - https://visualportfolio.co/responsive-hover-overlays/

Thank you for the information, I have fixed it already.

**Comment by jx1k** [comment]
Thanks for clearing that up! I found a css based workaround by now, but it's good to know if I ever go pro.
