### ISSUE TITLE
Avoid duplicates feature not working

### ISSUE THREAD

**Issue by yasserberrehail** [nk-crew/visual-portfolio#201]
Hello

Avoid duplicated feature isn't working.

Although marking it as enabled, when we go duplicate a project, both are displayed on the portfolio page.

**Comment by nk-o** [comment]
Hi,

I see it is working correctly https://visualportfolio.co/avoid-duplicates/

Feel free to provide a reproduction guide, which lets me see this issue locally.

Regards,
Nikita.
