### ISSUE TITLE
Add link to single page post in popup video or image

### ISSUE THREAD

**Issue by jx1k** [nk-crew/visual-portfolio#202]
I'm wondering if there is a way to add a link to the single page post in a popup. I have a gallery of videos that are displayed in the lightbox, but I'd like to link to the actual post to show some additional information.

I know I can set the title and description source, but those are not clickable.

Is this possible at all at the moment?

**Comment by nk-o** [comment]
Hi,

You can add a raw HTML here:
![Shot 2024-03-26 at 16 37 29](https://github.com/nk-crew/visual-portfolio/assets/14810891/ddc69557-58b3-4d29-8f02-237f27d5fe11)

**Comment by jx1k** [comment]
Thank you for your reply. I found another workaround that's better suited for my needs.
I've set the `Description Source` to `Item Description` and start each video post with a `More` block. This way the text of the `More` block works as a link to the full page post in the Fancybox.
