### ISSUE TITLE
Latest update 3.3.3 breaks post filters

### ISSUE THREAD

**Issue by mtressl** [nk-crew/visual-portfolio#206]
I am making heavy use of post filters to display a certain set of posts on various pages.
The latest update breaks this functionality (gallery on page, posts filtered by categories /tags) and the gallery appears empty.

**Comment by nk-o** [comment]
resolved in https://github.com/nk-crew/visual-portfolio/commit/8e5f0151cbff595827cb5adc8defe64808f943cd
