### ISSUE TITLE
conflict with oxygen

### ISSUE THREAD

**Issue by shawn313** [nk-crew/visual-portfolio#207]
when trying to access a project on the front end it loads up a different page https://crossregions.com under current projects you can see the project but if you click on them it goes to a different page if I try going to the project URL it goes to a different page if I disable oxygen and try the project URL it goes to the project

**Comment by nk-o** [comment]
I'm not interested in debugging a paid page builder on a custom installation. It would be helpful if you could provide more information on a fresh installation (not on your custom site).
