### ISSUE TITLE
Semantics and styles, better structure: No h2, figures, figcaptions, a wrap

### ISSUE THREAD

**Issue by whatsnewsisyphus** [nk-crew/visual-portfolio#89]
The current structure of portfolio items have some issues as described below. I would suggest something along the lines of
`
<a>

    <figure class="vp-portfolio__item">

        <div class="vp-portfolio__item-img-wrap">

            <img class="vp-portfolio__item-img"/>

        </div>

        <div class="vp-portfolio__item-overlay vp-portfolio__item-align-center">

                <figcaption class="vp-portfolio__item-meta">

                </figcaption>

        </div>

    </figure>
    
</a>
`

**The h2 is going to throw off a lot of people for various reasons:**
- Bad for semantic markup and SEO
- Is a heavily stylized element that will commonly be to large for grid usage and break the grid (See the [screenshot of what happens with base astra](https://user-images.githubusercontent.com/454772/50503735-172fd300-0a37-11e9-9b0b-80311be08390.png) )
*maybe add below here and have an option to remove it with ' Wrap lines on titles, might break even grids '
`.vp-portfolio__item-meta-title {
    white-space: nowrap;
}`

**Having the title be wrapped in a separate a/link element**
- Bad for semantic markup and SEO
- Creates two of the same link each element
- When you add data-srcset for responsive lightbox, it will also double that, ultimately causing a bit of bloat

**Solution above is easier to parse on the back and creates better html in the end.**

**Comment by nk-o** [comment]
I'll check this, thank you.

**Comment by whatsnewsisyphus** [comment]
Not sure if this is optimal, but an [example] (
http://photoswipe.com/documentation/seo.html) (you would wrap the a around
the image and caption)

**Comment by nk-o** [comment]
I'm not sure that `h2` tag could be removed, just because a lot of people already use the plugin and it may break a lot of portfolio styles on user's sites. `nowrap` is also is not a solution. In local build already added Grid layout, so you can use it instead of Masonry, so all rows will look good.

`figure` and `figcaption` already added in local build and will be available in plugin update.

**Comment by whatsnewsisyphus** [comment]
Can you add a filter that would allow changing the h2 without modifying
plugin files? It could also be done through vp settings with an option for
default caption element.
